name: reviewdog
on: [push]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ github.token }}
          reporter: github-check # Change reporter.
          level: error
          eslint_flags: 'src/'